var data = [{
    Analysis: {
        AeroMechanical: "",
        CFD: "",
        CoupledAeroMechanical: "",
        Structural: {
            Mechanical: {
                "2Dmodel_sim2_2D_DensityNotDefined_Errors": {
                    "hasMaterial, SolidMaterial": [
                        "AISI_Steel_4340",
                        "AISI_Steel_4340_1_Error",
                    ],
                    isTransient: false,
                    "hasStorageLocation, LocalStorage": [
                        "LocalStorage_id_num_1--2Dmodel_sim2_2D_DensityNotDefined_Errors",
                    ],
                    isHarmonic: false,
                    "hasBoundary, Boundary": [],
                    "hasMesh, Mesh": ["2Dmodel_fem2"],
                    ToolVersion: "v2206.0.0.1700",
                    "hasResult, Result": "",
                    LastModificationDate: 1658750583.3674643,
                    FileSize: 5945018,
                    isSteadyState: true,
                    "hasContributor, People": "",
                    FileNameOriginal: "2Dmodel_sim2",
                    FileNameAlias: "2Dmodel_sim2_2D_DensityNotDefined_Errors",
                    hasSource: "SIM",
                    SolutionType: "SOL 103 Real Eigenvalues",
                    is2D: true,
                    is3D: false,
                },
            },
            Thermomechanical: "",
        },
    },
    Material: {
        FluidMaterial: "",
        SolidMaterial: {
            AISI_Steel_4340: {
                Description: "",
                "Material properties": "",
                "Referenced library material": "physicalmateriallibrary.xml",
                "Library Version": "7.0",
                "Material Type": "Isotropic",
                Label: "1",
                "Alternate Name": "",
                "Material Property Dependency": "Constant",
                "Stress-Strain Format Type": "Stress-Strain Curve",
                "Stress-Strain Input Data Type": "Engineering Stress-Strain",
                "Strain Rate Dependency": "Symonds and Cowper",
                "Failure flag": "(0) Failure is not considered",
                "Failure Thinning Strain (EPSTHIN)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Failure Major In-plane Strain (EPSMAJ)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Effective Plastic Strain for eroding elements (FS)": {
                    Magnitude: "1e+20",
                    Unit: "mm/mm",
                },
                "Formulation for rate effects (VP)": "(0) Scale Yield Effects",
                "Plastic hardening modulus (EH)": {
                    Magnitude: "0",
                    Unit: "MPa",
                },
                "Effective plastic strain in weld material at failure (EFAIL)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Failure Determination Method": "(0) Maximum Tensile Strain",
                "Stiffness Damping Ratio (DAMP)": "0",
                "Filtering Factor (RFAC)": "0",
                "RTCL Damage (EPSO)": "Inactive",
                "Transverse Shear (TSMD)": {
                    Magnitude: "0.9",
                    Unit: "mm/mm",
                },
                "Mechanical Power to Heat Ratio": "0",
                "Stress-Life Data": "Coefficients",
                "Strain-Life Data": "Coefficients",
                "Percent Reduction in Area": "0",
                "R-Ratio": "Specify",
                "Test Type": "Tension",
                "Survival Probability": "50",
                "Tsigma (90/10)": "1.5",
                R0: "2.5",
                R45: "3",
                R90: "2.7",
                "Bend Radii - SI Material Stock": "No Field",
                "Bend Radii - English Material Stock": "No Field",
                Model: "None",
                "Viscoplastic Type": "None",
                "Plastic Damage Option": "Linear Damage",
                "Softening Plastic Strain (EPPF)": {
                    Magnitude: "1e+12",
                    Unit: "mm/mm",
                },
                "Rupture Plastic Strain (EPPFR)": {
                    Magnitude: "1e+14",
                    Unit: "mm/mm",
                },
                Alpha: "0",
                Beta: "0",
                Gamma: {
                    Magnitude: "0",
                    Unit: "MPa^-1",
                },
                D0: "0",
                B: "0",
                Lambda: "0",
                Ds: "0",
                "Dynamic Viscosity Control": "Constant or Temperature",
                "Pressure Cutoff (PC)": {
                    Magnitude: "0",
                    Unit: "MPa",
                },
                "Studio Material": "Steel",
                "Fixed Stock Thickness": "false",
                Adhesive: "",
                "Process Note": "",
                "Heat Generation": "false",
                "Progressive Failure Model": "None",
                "*Material Card Option (OPTION)": "*MAT_ELASTIC",
                "Fiber Action (2WAY)": "Unidirectional",
                "Transversal Isotropic Behavior Flag (TI)": "Unidirectional",
                "Material Softening Reduction (SOFT)": "1",
                "Compression Reduction Factor (YCFAC)": "2",
                DFAILT: "0.0",
                "Minimum Time Step (TDEL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Failing Integration Points Option": "Number",
                "Number of Failing Integration Points for Shell Deletion (NUMINT)": "0",
                "Tension (TEROD)": "0",
                "Compression (CEROD)": "0",
                "Adiabatic Temperature Option (CP)": "Calculation Disabled",
                Limit: "No Limit",
                "Flag (IPS)": "No Prestrain Added",
                "Time for Joint Failure (TFAIL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Time Step Size for Mass Scaling (DT)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Time Step Size Criteria (TFAIL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Failure Criterion (CRIT)": "Chang-Chang",
                "Strain Rate Averaging Opt (DT)": "Running average",
                "Include Additional Damage Fields": "false",
                "Damage Option (DMGOPT)": "Plastic Strain based Damage (0)",
                "Weld Assembly Failure Flag (ASFF)": "Damaged Elements Fail Individually",
                "Orthogonal Softening (SOFT2)": "1",
                "Softening Reduction Factor (SOFTG)": "1",
                "Number of Cycles (NCYRED)": "1",
                "Rigid Body Coupling Flag (N)": "Normal LS-DYNA Updates",
                "Coupling Option (COUPLE)": "Undeformed Geometry Corresponds to Local MADYMO 5.4 / CAL3D",
                "MADYMO Reference Number (RE)": "",
                "Update Flag (M)": "Normal LS-DYNA Rigid Body updates",
                "Translational Stiffness along r-Axis (TKR)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Translational Stiffness along s-Axis (TKS)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Translational Stiffness along t-Axis (TKT)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Rotational Stiffness about r-Axis (RKR)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Rotational Stiffness about s-Axis (RKS)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Rotational Stiffness about t-Axis (RKT)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Material Axes Option (AOPT)": "Locally Orthotropic with Material Axes using Element Nodes",
                "Material Axes Change Flag (MACF)": "No Change",
                "Material Axis Tracking (ATRACK)": "A-Axis Rotates with Element",
                hasSource: "FEM, DAT",
                MaterialCategory: "METAL",
                MaterialSubCategory: "Carbon Steel",
                "hasQuantitativeMetric, Density": [
                    "Density_7.85e-06_AISI_Steel_4340",
                ],
                "hasQuantitativeMetric, ModulusOfElasticity": [
                    "ModulusOfElasticity_193000000_AISI_Steel_4340",
                ],
                PoissonRatio: "0.284",
                TypeOfNonlinearity: "Elastoplastic",
                YieldFunctionCriterion: "von Mises",
                HardeningRule: "Isotropic",
                "hasQuantitativeMetric, YieldStrength": [
                    "YieldStrength_1178000_AISI_Steel_4340",
                ],
                "hasQuantitativeMetric, UltimateTensileStrength": [
                    "UltimateTensileStrength_1240000_AISI_Steel_4340",
                ],
                "hasQuantitativeMetric, FatigueStrengthCoefficient": [
                    "FatigueStrengthCoefficient_1917000_AISI_Steel_4340",
                ],
                FatigueStrengthExponent: "-0.099",
                FatigueDuctilityCoefficient: "1.122",
                FatigueDuctilityExponent: "-0.72",
                "hasQuantitativeMetric, CyclicStrengthCoefficient": [
                    "CyclicStrengthCoefficient_1887000_AISI_Steel_4340",
                ],
                CyclicStrainHardeningExponent: "0.137",
                "hasQuantitativeMetric, InitialStrain": [
                    "InitialStrain_0.02_AISI_Steel_4340",
                ],
                HardeningExponent: "0.22",
                "hasQuantitativeMetric, StrengthCoefficient": [
                    "StrengthCoefficient_2182.004_AISI_Steel_4340",
                ],
                ThermalExpansionCoefficientType: "Undefined",
                "hasQuantitativeMetric, ThermalExpansionCoefficient": [
                    "ThermalExpansionCoefficient_1.23e-05_AISI_Steel_4340",
                ],
                "hasQuantitativeMetric, ThermalConductivity": [
                    "ThermalConductivity_44500_AISI_Steel_4340",
                ],
                "hasQuantitativeMetric, SpecificHeat": [
                    "SpecificHeat_475000000_AISI_Steel_4340",
                ],
                CrosshatchPattern: "Steel",
            },
            AISI_Steel_4340_1_Error: {
                Description: "",
                "Parent Material": "AISI_Steel_4340",
                "Parent Material Library": "physicalmateriallibrary.xml",
                "Parent Material Library Version": "7.0",
                "Material properties": "",
                "Material defined in component": "2Dmodel_fem2",
                "Material Type": "Isotropic",
                Label: "2",
                "Alternate Name": "",
                "Material Property Dependency": "Constant",
                "Failure flag": "(0) Failure is not considered",
                "Failure Thinning Strain (EPSTHIN)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Failure Major In-plane Strain (EPSMAJ)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Plastic hardening modulus (EH)": {
                    Magnitude: "0",
                    Unit: "MPa",
                },
                "Effective plastic strain in weld material at failure (EFAIL)": {
                    Magnitude: "0",
                    Unit: "mm/mm",
                },
                "Failure Determination Method": "(0) Maximum Tensile Strain",
                "Stiffness Damping Ratio (DAMP)": "0",
                "Filtering Factor (RFAC)": "0",
                "RTCL Damage (EPSO)": "Inactive",
                "Transverse Shear (TSMD)": {
                    Magnitude: "0.9",
                    Unit: "mm/mm",
                },
                "Mechanical Power to Heat Ratio": "0",
                "Stress-Life Data": "Coefficients",
                "Strain-Life Data": "Coefficients",
                "Percent Reduction in Area": "0",
                "R-Ratio": "Specify",
                "Test Type": "Tension",
                "Survival Probability": "50",
                "Tsigma (90/10)": "1.5",
                R0: "2.5",
                R45: "3",
                R90: "2.7",
                "Bend Radii - SI Material Stock": "No Field",
                "Bend Radii - English Material Stock": "No Field",
                Model: "None",
                "Viscoplastic Type": "None",
                Alpha: "0",
                Beta: "0",
                Gamma: {
                    Magnitude: "0",
                    Unit: "MPa^-1",
                },
                D0: "0",
                B: "0",
                Lambda: "0",
                Ds: "0",
                "Dynamic Viscosity Control": "Constant or Temperature",
                "Pressure Cutoff (PC)": {
                    Magnitude: "0",
                    Unit: "MPa",
                },
                "Studio Material": "Steel",
                "Fixed Stock Thickness": "false",
                Adhesive: "",
                "Process Note": "",
                "Heat Generation": "false",
                "Progressive Failure Model": "None",
                "*Material Card Option (OPTION)": "*MAT_ELASTIC",
                "Fiber Action (2WAY)": "Unidirectional",
                "Transversal Isotropic Behavior Flag (TI)": "Unidirectional",
                "Material Softening Reduction (SOFT)": "1",
                "Compression Reduction Factor (YCFAC)": "2",
                DFAILT: "0.0",
                "Minimum Time Step (TDEL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Failing Integration Points Option": "Number",
                "Number of Failing Integration Points for Shell Deletion (NUMINT)": "0",
                "Tension (TEROD)": "0",
                "Compression (CEROD)": "0",
                "Adiabatic Temperature Option (CP)": "Calculation Disabled",
                Limit: "No Limit",
                "Flag (IPS)": "No Prestrain Added",
                "Time for Joint Failure (TFAIL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Time Step Size for Mass Scaling (DT)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Time Step Size Criteria (TFAIL)": {
                    Magnitude: "0",
                    Unit: "s",
                },
                "Failure Criterion (CRIT)": "Chang-Chang",
                "Strain Rate Averaging Opt (DT)": "Running average",
                "Include Additional Damage Fields": "false",
                "Damage Option (DMGOPT)": "Plastic Strain based Damage (0)",
                "Weld Assembly Failure Flag (ASFF)": "Damaged Elements Fail Individually",
                "Orthogonal Softening (SOFT2)": "1",
                "Softening Reduction Factor (SOFTG)": "1",
                "Number of Cycles (NCYRED)": "1",
                "Rigid Body Coupling Flag (N)": "Normal LS-DYNA Updates",
                "Coupling Option (COUPLE)": "Undeformed Geometry Corresponds to Local MADYMO 5.4 / CAL3D",
                "MADYMO Reference Number (RE)": "",
                "Update Flag (M)": "Normal LS-DYNA Rigid Body updates",
                "Translational Stiffness along r-Axis (TKR)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Translational Stiffness along s-Axis (TKS)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Translational Stiffness along t-Axis (TKT)": {
                    Magnitude: "0",
                    Unit: "N/mm",
                },
                "Rotational Stiffness about r-Axis (RKR)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Rotational Stiffness about s-Axis (RKS)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Rotational Stiffness about t-Axis (RKT)": {
                    Magnitude: "0",
                    Unit: "N-mm/deg",
                },
                "Material Axes Option (AOPT)": "Locally Orthotropic with Material Axes using Element Nodes",
                "Material Axes Change Flag (MACF)": "No Change",
                "Material Axis Tracking (ATRACK)": "A-Axis Rotates with Element",
                hasSource: "FEM, DAT",
                MaterialCategory: "METAL",
                MaterialSubCategory: "Carbon Steel",
                "hasQuantitativeMetric, ModulusOfElasticity": [
                    "ModulusOfElasticity_193000000_AISI_Steel_4340_1_Error",
                ],
                PoissonRatio: "0.284",
                TypeOfNonlinearity: "Nonlinear elastic",
                "hasQuantitativeMetric, YieldStrength": [
                    "YieldStrength_1178000_AISI_Steel_4340_1_Error",
                ],
                "hasQuantitativeMetric, UltimateTensileStrength": [
                    "UltimateTensileStrength_1240000_AISI_Steel_4340_1_Error",
                ],
                "hasQuantitativeMetric, FatigueStrengthCoefficient": [
                    "FatigueStrengthCoefficient_1917000_AISI_Steel_4340_1_Error",
                ],
                FatigueStrengthExponent: "-0.099",
                FatigueDuctilityCoefficient: "1.122",
                FatigueDuctilityExponent: "-0.72",
                "hasQuantitativeMetric, CyclicStrengthCoefficient": [
                    "CyclicStrengthCoefficient_1887000_AISI_Steel_4340_1_Error",
                ],
                CyclicStrainHardeningExponent: "0.137",
                "hasQuantitativeMetric, InitialStrain": [
                    "InitialStrain_0.02_AISI_Steel_4340_1_Error",
                ],
                HardeningExponent: "0.22",
                "hasQuantitativeMetric, StrengthCoefficient": [
                    "StrengthCoefficient_2182.004_AISI_Steel_4340_1_Error",
                ],
                ThermalExpansionCoefficientType: "Undefined",
                "hasQuantitativeMetric, ThermalExpansionCoefficient": [
                    "ThermalExpansionCoefficient_1.23e-05_AISI_Steel_4340_1_Error",
                ],
                "hasQuantitativeMetric, ThermalConductivity": [
                    "ThermalConductivity_44500_AISI_Steel_4340_1_Error",
                ],
                "hasQuantitativeMetric, SpecificHeat": [
                    "SpecificHeat_475000000_AISI_Steel_4340_1_Error",
                ],
                CrosshatchPattern: "Steel",
            },
        },
    },
    Boundary: {},
    People: "",
    Geometry: {
        "2Dmodel_fem2_i": {
            is2D: true,
            is3D: false,
            LastModificationDate: 1613118225.0,
            FileSize: 37850,
            FileNameOriginal: "2Dmodel_fem2_i",
            FileNameAlias: "2Dmodel_fem2_i",
            hasSource: "PRT",
            isAssembly: false,
            "hasMaterial, SolidMaterial": [
                "AISI_Steel_4340",
                "AISI_Steel_4340_1_Error",
            ],
            "hasGeometricFeature, Edge": [
                "LOADINGEDGE--2Dmodel_fem2_i",
                "TOPEDGE--2Dmodel_fem2_i",
            ],
            "hasCADFeatureSequenceTree, CADFeatureSequenceTree": [
                "DATUM_CSYS(0)--2Dmodel_fem2_i",
                "SKETCH(1:1B)--2Dmodel_fem2_i",
            ],
            "hasCADFeatureSequenceTree, SketchFeature": [
                "SKETCH(1)--2Dmodel_fem2_i",
            ],
            "hasCADFeatureSequenceTree, Extrude": ["EXTRUDE(2)--2Dmodel_fem2_i"],
        },
    },
    Loads: {
        CyclicLoads: "",
        HeatFlux: "",
        MomentLoad: "",
        PointLoad: "",
        PressureLoad: "",
        UDL: "",
    },
    Mesh: {
        "2Dmodel_fem2": {
            "hasMeshVolume, MeshVolume": ["2d_mesh(1)--2Dmodel_fem2"],
            LastModificationDate: 1658750583.0554657,
            FileSize: 3201235,
            is2D: true,
            is3D: false,
            FileNameOriginal: "2Dmodel_fem2",
            FileNameAlias: "2Dmodel_fem2",
            hasSource: "FEM",
        },
    },
    Preprocessing: "",
    Result: "",
    StorageLocation: {
        CloudStorage: "",
        LocalStorage: {
            "LocalStorage_id_num_1--2Dmodel_sim2_2D_DensityNotDefined_Errors": {
                GID: "z003hz2y",
                MachineName: "md1w08fc",
            },
        },
        ServerStorage: "",
        TeamcenterStorage: "",
    },
    Supplier: "",
    QuantitativeMetric: {
        Angle: "",
        CyclicStrengthCoefficient: {
            CyclicStrengthCoefficient_1887000_AISI_Steel_4340: {
                hasMagnitude: "1887000",
                hasUnit: "kPa",
            },
            CyclicStrengthCoefficient_1887000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "1887000",
                hasUnit: "kPa",
            },
        },
        Density: {
            "Density_7.85e-06_AISI_Steel_4340": {
                hasMagnitude: "7.85e-06",
                hasUnit: "kg/mm^3",
            },
        },
        ElasticStrength: "",
        FatigueStrengthCoefficient: {
            FatigueStrengthCoefficient_1917000_AISI_Steel_4340: {
                hasMagnitude: "1917000",
                hasUnit: "kPa",
            },
            FatigueStrengthCoefficient_1917000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "1917000",
                hasUnit: "kPa",
            },
        },
        Force: "",
        Height: "",
        Independent: "",
        InitialStrain: {
            "InitialStrain_0.02_AISI_Steel_4340": {
                hasMagnitude: "0.02",
                hasUnit: "mm/mm",
            },
            "InitialStrain_0.02_AISI_Steel_4340_1_Error": {
                hasMagnitude: "0.02",
                hasUnit: "mm/mm",
            },
        },
        Length: {
            "ElementSize_5mm--2Dmodel_fem2": {
                hasMagnitude: 5.0,
                hasUnit: "mm",
            },
        },
        Mass_Flow: "",
        ModulusOfElasticity: {
            ModulusOfElasticity_193000000_AISI_Steel_4340: {
                hasMagnitude: "193000000",
                hasUnit: "kPa",
            },
            ModulusOfElasticity_193000000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "193000000",
                hasUnit: "kPa",
            },
        },
        Moment: "",
        PoissonRatioArray: "",
        Pressure: "",
        ShearModulus: "",
        SpecificHeat: {
            SpecificHeat_475000000_AISI_Steel_4340: {
                hasMagnitude: "475000000",
                hasUnit: "microJ/(kg-K)",
            },
            SpecificHeat_475000000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "475000000",
                hasUnit: "microJ/(kg-K)",
            },
        },
        StrengthCoefficient: {
            "StrengthCoefficient_2182.004_AISI_Steel_4340": {
                hasMagnitude: "2182.004",
                hasUnit: "MPa",
            },
            "StrengthCoefficient_2182.004_AISI_Steel_4340_1_Error": {
                hasMagnitude: "2182.004",
                hasUnit: "MPa",
            },
        },
        Stress: "",
        Temperature: "",
        ThermalConductivity: {
            ThermalConductivity_44500_AISI_Steel_4340: {
                hasMagnitude: "44500",
                hasUnit: "microW/(mm-degC)",
            },
            ThermalConductivity_44500_AISI_Steel_4340_1_Error: {
                hasMagnitude: "44500",
                hasUnit: "microW/(mm-degC)",
            },
        },
        ThermalExpansionCoefficient: {
            "ThermalExpansionCoefficient_1.23e-05_AISI_Steel_4340": {
                hasMagnitude: "1.23e-05",
                hasUnit: "degC^-1",
            },
            "ThermalExpansionCoefficient_1.23e-05_AISI_Steel_4340_1_Error": {
                hasMagnitude: "1.23e-05",
                hasUnit: "degC^-1",
            },
        },
        Thickness: "",
        TurbulenceIntensity: "",
        UltimateTensileStrength: {
            UltimateTensileStrength_1240000_AISI_Steel_4340: {
                hasMagnitude: "1240000",
                hasUnit: "kPa",
            },
            UltimateTensileStrength_1240000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "1240000",
                hasUnit: "kPa",
            },
        },
        Velocity: "",
        Viscosity: "",
        Width: "",
        XDirection: "",
        YDirection: "",
        YieldStrength: {
            YieldStrength_1178000_AISI_Steel_4340: {
                hasMagnitude: "1178000",
                hasUnit: "kPa",
            },
            YieldStrength_1178000_AISI_Steel_4340_1_Error: {
                hasMagnitude: "1178000",
                hasUnit: "kPa",
            },
        },
        ZDirection: "",
    },
    BoundaryCondition: {
        FEABoundaryCondition: {
            FEAConstraintBC: {
                AntiSymmetricConstraint: "",
                AutomaticCoupling: "",
                CylindricalConstraint: "",
                EnforcedDisplacementConstraint: "",
                FixedConstraint: "",
                FixedRotationConstraint: "",
                FixedTranslationConstraint: "",
                ManualCoupling: "",
                PinnedConstraint: "",
                RollerConstraint: "",
                SimplySupportedConstraint: "",
                SliderConstraint: "",
                SymmetricConstraint: "",
                UserDefinedConstraint: "",
            },
            FEAInteractionBC: {
                MechanicalContact: "",
                ThermalContact: "",
            },
        },
        CFDBoundaryCondition: {
            CFDConstraintBC: {
                FrictionWallBC: "",
                TotalPressureBC: "",
                VelocityBC: "",
                MassFlowBC: "",
                MovingWallBC: "",
                SmoothWallBC: "",
                StationaryWallBC: "",
            },
            CFDInteractionBC: "",
        },
        GenericBoundaryCondition: {
            PressureBC: "",
        },
    },
    PostProcessing: {
        Parameters: {
            CFDParameters: {
                AreaAveragedDynamicPressure: "",
                AreaAveragedPressure: "",
                AreaAveragedTotalPressure: "",
                MassAveragedDynamicPressure: "",
                MassAveragedPressure: "",
                MassAveragedTotalPressure: "",
                MassFlowRate: "",
            },
            FEAParameters: {
                DisplacementNodal: "",
                ReactionForceNodal: "",
                ReactionMomentNodal: "",
                RotationNodal: "",
                StressElementNodal: "",
                StressElemental: "",
            },
            GenericParameters: {
                MaxTemperature: "",
            },
        },
        Plots: {
            ContourPlots: {
                ContactPressureContour: "",
                ContactStatusContour: "",
                PressureContour: "",
                TotalPressureContour: "",
                VelocityContour: "",
            },
            DisplacementPlot: "",
            XYPlots: {
                MassAveragedTotalPressurePlot: "",
                WallYPlus: "",
            },
            StressPlot: {
                PrincipalStressPlot: "",
                VonMisesStressPlot: "",
            },
            StrainPlot: "",
        },
    },
    MeshElements: {
        AxiSymmetricElement: "",
        HexElement: "",
        PrismLayer: "",
        QuadElement: {
            "CQUAD8--2Dmodel_fem2": {},
        },
        ShellElement: "",
        TetrahedralElement: "",
    },
    GeometricFeature: {
        Body: "",
        Curve: "",
        Edge: {
            "LOADINGEDGE--2Dmodel_fem2_i": {},
            "TOPEDGE--2Dmodel_fem2_i": {},
        },
        Face: "",
        Line: {
            "Line4--2Dmodel_fem2_i": {
                Name: "Line4",
                GeometricFeatureType: "Line",
                Length: 100.00000000000001,
                StartPoint: "[0.0, 0.0, 100.0]",
                EndPoint: "[0.0, 0.0, 0.0]",
            },
        },
        Point: "",
    },
    CADFeatureSequenceTree: {
        Extrude: {
            "EXTRUDE(2)--2Dmodel_fem2_i": {
                BodyType: "Extrude",
                BooleanOperationParameter: "NXOpen.GeometricUtilities.BooleanOperationBooleanType.Create",
                EndLimit: 300.0,
                EndTrimType: "NXOpen.GeometricUtilities.ExtendExtendType.Value",
                StartLimit: 0.0,
                StartTrimType: "NXOpen.GeometricUtilities.ExtendExtendType.Value",
                hasXDirection: 1.0,
                hasYDirection: 0.0,
                hasZDirection: 0.0,
            },
        },
        Revolve: "",
        SketchFeature: {
            "SKETCH(1)--2Dmodel_fem2_i": {},
        },
        "DATUM_CSYS(0)--2Dmodel_fem2_i": {
            "hasCADExpression, Expression": [],
            "hasEntities, Entity": [],
            "hasAllChildren, CADFeatureSequenceTree": ["SKETCH(1)--2Dmodel_fem2_i"],
            "hasParents, CADFeatureSequenceTree": [],
            "hasImmediateChildren, CADFeatureSequenceTree": [
                "SKETCH(1:1B)--2Dmodel_fem2_i",
            ],
            CADFeatureType: "DatumCsys",
            FeatureName: "Datum Coordinate System(0)",
        },
        "SKETCH(1:1B)--2Dmodel_fem2_i": {
            "hasCADExpression, Expression": [],
            "hasEntities, Entity": [],
            "hasAllChildren, CADFeatureSequenceTree": [],
            "hasParents, CADFeatureSequenceTree": [],
            "hasImmediateChildren, CADFeatureSequenceTree": [
                "SKETCH(1)--2Dmodel_fem2_i",
            ],
            CADFeatureType: "DatumCsys",
            FeatureName: "Datum Coordinate System(1)",
        },
    },
    Expression: {
        "p0--2Dmodel_fem2_i": {
            Description: "(Extrude(2) Start Limit)",
            ExpressionType: "Number",
            Name: "p0",
            Value: 0.0,
        },
        "p1--2Dmodel_fem2_i": {
            Description: "(Extrude(2) End Limit)",
            ExpressionType: "Number",
            Name: "p1",
            Value: 300.0,
        },
    },
    Relation: {
        CohesionRelation: "",
        ExactRelation: "",
    },
    KnowledgeSource: {
        Customer: "",
        DataHandbook: "",
        KS_Analysis: "",
        OpenLiterature: "",
        SimulationExpert: "",
    },
    Documentation: {
        ConfluencePage: "",
        PPT: "",
    },
    Error: "",
    GeometricHierarchy: {},
    MeshVolume: {
        "2d_mesh(1)--2Dmodel_fem2": {
            Mesh_Collector: "ThinShell(1)",
            Mesh_name: "2d_mesh(1)",
            "Surface Curvature Based Size Variation": "NA",
            "Surface Curvature Threshold": "NA",
            "hasMeshElement, MeshElements": ["CQUAD8--2Dmodel_fem2"],
            is2D: true,
            is3D: false,
            MinElementLength: "NA",
            NumElements: "1200",
            NumNodes: "3761",
            "hasElementSize, Length": ["ElementSize_5mm--2Dmodel_fem2"],
            "hasMaterial, SolidMaterial": ["AISI_Steel_4340_1_Error"],
        },
    },
    Project: {
        Errors: {
            "hasContributor, People": "",
            "hasAnalysis, Mechanical": ["2Dmodel_sim2_2D_DensityNotDefined_Errors"],
            "hasUpdateEvent, UpdateEvent": [
                "UpdateEvent_id_num_1--2Dmodel_sim2_2D_DensityNotDefined_Errors",
            ],
        },
    },
    UpdateEvent: {
        UpdateEvent_id_num_1: {
            Comment: "",
            hasPredecessor: "",
            hasSuccessor: "",
        },
    },
    SystemSettings: {
        SystemSettings_id_num_1: {
            OS: "Windows",
            OSRelease: "10",
            OSVersion: "10.0.19041",
            OSPlatform: "Windows-10-10.0.19041-SP0",
            Processor: "Intel64 Family 6 Model 142 Stepping 10, GenuineIntel",
            ProcessorArchitecture: "AMD64",
            EnvVariables: "ADAPTIVACLIENT, ALLUSERSPROFILE, APPDATA, APPLOGSC, APPLOGSU, CHOCOLATEYINSTALL, CHOCOLATEYLASTPATHUPDATE, COMMONPROGRAMFILES, COMMONPROGRAMFILES(X86), COMMONPROGRAMW6432, COMPUTERNAME, COMSPEC, DEFAULTSCREENSAVER, DESKTOP, DRIVERDATA, DRT_DATABASE_PASSWORD, DRT_DATABASE_USERNAME, FLEXLM_TIMEOUT, F_IA32_REDIST11, GYP_MSVS_VERSION, HOMEDRIVE, HOMEPATH, IDEA_INITIAL_DIRECTORY, INTEL_DEV_REDIST, JAVA_HOME, LOCALAPPDATA, LOG4J_FORMAT_MSG_NO_LOOKUPS, LOGONSERVER, NETLOGON, NETLOGONDWP, NO_PROXY, NUMBER_OF_PROCESSORS, ONEDRIVE, ONEDRIVECOMMERCIAL, OS, PATH, PATHEXT, PDFTK_PATH, PROCESSOR_ARCHITECTURE, PROCESSOR_IDENTIFIER, PROCESSOR_LEVEL, PROCESSOR_REVISION, PROGRAMDATA, PROGRAMFILES, PROGRAMFILES(X86), PROGRAMW6432, PROMPT, PSMODULEPATH, PUBLIC, PYCHARM_HOSTED, PYTHONIOENCODING, PYTHONPATH, PYTHONUNBUFFERED, SESSIONNAME, SITESERVER, SPLM_LICENSE_SERVER, SYSTEMDRIVE, SYSTEMROOT, TCVIS_LICENSE_SERVER, TEMP, TMP, UATDATA, UGII_BASE_DIR, UGII_CPP_SKIP_UFUNC_EXECUTE_CHECK, UGII_LANG, UGS_LICENSE_BUNDLE, USERDNSDOMAIN, USERDOMAIN, USERDOMAIN_ROAMINGPROFILE, USERNAME, USERPROFILE, V2020OSLOC, VBOX_MSI_INSTALL_PATH, VIRTUAL_ENV, WINDIR, ZSWCENTERLOC, _OLD_VIRTUAL_PATH, _OLD_VIRTUAL_PROMPT",
            "RAM(GB)": 31.85,
            UGII_BASE_DIR: "C:\\Program Files\\Siemens\\Simcenter3D_2206",
        },
    },
}, ];
d3.jsonldVis(data, "#graph", {
    w: 800,
    h: 600,
    maxLabelWidth: 250,
    tipClassName: "tip-class",
});